### ISSUE TITLE
How do I get Start URL to show on data?

### ISSUE THREAD

**Issue by Qewar** [hejiheji001/Web-Scraper-Plus#13]
The original Web Scraper tool has it so on the data it has the Start URL so you know where the data was taken from, this is not the case with this forked tool, or at least I'm not finding a way how.

Original
![image](https://user-images.githubusercontent.com/50082459/103909551-c2ca8e00-50fb-11eb-8444-1a3b70f2fe2d.png)

Forked
![image](https://user-images.githubusercontent.com/50082459/103909431-96af0d00-50fb-11eb-9ed5-22220b325257.png)

I need to know the URL from the corresponding data so I know what URL's have the 404 error.

**Comment by hejiheji001** [comment]
I think you can add a location.href as part of your data. It will record the scraping url.

**Comment by hejiheji001** [comment]
https://github.com/hejiheji001/Web-Scraper-Plus/wiki/Data-Filter

**Comment by Qewar** [comment]
> I think you can add a location.href as part of your data. It will record the scraping url.

Worked perfectly, thanks.
