### ISSUE TITLE
Failed to Load Extension because of CSSSelector.JS

### ISSUE THREAD

**Issue by TheMrugraj** [hejiheji001/Web-Scraper-Plus#7]
Do anyone have any idea on this?

![image](https://user-images.githubusercontent.com/6426983/57448875-1b3aef80-7278-11e9-9f67-8d5d3465a72c.png)

**Comment by TheMrugraj** [comment]
I had the other Repo with CssSelector.JS so just copied and placed at the same location but, still now, I am getting below error in console when I try to enable Selection mode.

`Error handling response: TypeError: Cannot read property 'CSSSelector' of null`

![image](https://user-images.githubusercontent.com/6426983/57449185-f2672a00-7278-11e9-854e-c32f3482f785.png)

**Comment by ibraheemhsn** [comment]
looks like error related to brwoser.
try to reinstall plugin in canary version of chrome.

**Comment by TheMrugraj** [comment]
I tried there as well. But, it is still not working.

**Comment by TheMrugraj** [comment]
I think there is some issue with the `CssSelector.js` which I explicitly placed at the path. Does anyone have actual CssSelector.js which is suppose to be use here.

**Comment by hejiheji001** [comment]
Have you tried to download this Extension as zip and install from Chrome manually?
